---
- hosts: 'windows_dcs'
  roles:
    - role: cyberark.conjur-host-identity
      conjur_appliance_url: 'https://master.nate.lab/api'
      conjur_account: 'CYBR'
      conjur_host_factory_token: '3d4rgcbq1an3b10rkq471tnn5jt1rfn23y2r56e0try9fen143xhd7'
      conjur_host_name: "{{inventory_hostname}}"
      conjur_ssl_certificate: "-----BEGIN CERTIFICATE-----
MIIE3TCCAsWgAwIBAgICEjQwDQYJKoZIhvcNAQELBQAwcTELMAkGA1UEBhMCVVMx
CzAJBgNVBAgMAk1BMQ0wCwYDVQQKDARDWUJSMQ8wDQYDVQQLDAZEZXZPUHMxFDAS
BgNVBAMMC2NhLm5hdGUubGFiMR8wHQYJKoZIhvcNAQkBFhBuYXRlQGNhLm5hdGUu
bGFiMB4XDTE4MDQyMzE5MzMxMloXDTE5MDQyMzE5MzMxMlowdTELMAkGA1UEBhMC
VVMxCzAJBgNVBAgMAk1BMQ0wCwYDVQQKDARDWUJSMQ8wDQYDVQQLDAZEZXZPUHMx
GDAWBgNVBAMMD21hc3Rlci5uYXRlLmxhYjEfMB0GCSqGSIb3DQEJARYQbmF0ZUBj
YS5uYXRlLmxhYjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOJNVoHw
TR0qla1X2MF3XZ8ddDd13iZivzRVHSZH91TGBgqcvXY8dTQ9MIud1JCIuzJVpNbM
l+zoxd5GIGYM/AyEYARF2l5NGLeG4LeYpc+qsm/IGOVFSscVPhJKuA/aKDmU07Nc
PtaclSdwFUsNd1PVnUaoqwLdNdYwcAvR5J/zVi4xkBBNFGcoKrmP4UzivWOJjCd3
zhhEHCIAEUTcLsMSpiBOOgFDP24SEMizp5WA+Me2QgYJrUdfp5S/CbPMpbblrx4V
8hrzCI5QcHC4GCVwcwHcvp9f/aGeS9En0QawMUpH0H563UfwpzvyM4leXlQxre0P
qXy74pCgeYKsbzcCAwEAAaN7MHkwCQYDVR0TBAIwADAsBglghkgBhvhCAQ0EHxYd
T3BlblNTTCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFBa5Zl7yHcYK
fV51aD7+ZhPFPUH+MB8GA1UdIwQYMBaAFBO5jb/I4vUWukwqvU0Bf9qLMf90MA0G
CSqGSIb3DQEBCwUAA4ICAQBWzpkR65RO7ICmeGKHo8QcsKAgdGKOnMZ8BCzppKNg
dD5zzo7UprU3wuVQPEKyBC5c5neiCrZxcRjPPlOjvibuFsxXpIf/xIq6pGd3ajAE
fbA3z96DMczkuMNrZczIX6vTl4TEw36aoJp/FPYBpNP7T/TgInPZfAKZ9JwxTgjf
vPGV2HYSefZi85ApiZ2QjRo++Gco3udap+VEXT+CER9Q6++vWsUw397EQEt3UT5K
KpXtnRhyShvGhpGvIo2lVHrsPKoFeFMmVdNsi/ZyXBREGNSRpB4bzAp2MZWO4CYu
2FCvhjHqYt+6B6fcqUZg5EtcpdR+hngAZ2Uv+j3aVBettJtAca4HjhtCQ6ndKUFj
Q2BLBf9A+t3GukrUosWV7xrefsc/ctDmCWi4WamgzwWzv9NTb5+wwkJzdgilePAS
Vqav061qJRhJFdRqcvZeO828Q6Y0+UOyR1XJj1v5fecDPhD9XrIpFeya2Y1W/PRG
JrakxH6tH5eMTYY7dP+K/9xlh8yzbH9I9Y/vr3rS9SE1qavjKeiGtBhO8u+PFDSB
/s9r83dEffsw615me/7ibg5Z0V/k2JP1PNaZXjpsY6XjFBCuimGB+s5+Cl5ET1ST
0Q5OdMpgMnBeduAZWWrVZr+cs5Yieq1/T7z49Eo+JCThqdvdUk3PPbIiejUGOU3p
Zg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFrTCCA5WgAwIBAgIBADANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJVUzEL
MAkGA1UECAwCTUExDTALBgNVBAoMBENZQlIxDzANBgNVBAsMBkRldk9QczEUMBIG
A1UEAwwLY2EubmF0ZS5sYWIxHzAdBgkqhkiG9w0BCQEWEG5hdGVAY2EubmF0ZS5s
YWIwHhcNMTgwNDIzMTkzMDM2WhcNMjgwNDIwMTkzMDM2WjBxMQswCQYDVQQGEwJV
UzELMAkGA1UECAwCTUExDTALBgNVBAoMBENZQlIxDzANBgNVBAsMBkRldk9QczEU
MBIGA1UEAwwLY2EubmF0ZS5sYWIxHzAdBgkqhkiG9w0BCQEWEG5hdGVAY2EubmF0
ZS5sYWIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD4ielIaJXH//hs
DEP4erbkBC0eR0cEufcWErNK6STyL9y3j9Yr4/PiXMCS+BQ52TLe7uMnRhtuvE+M
5gMfr3ZTSs1fGmlZnZvnZqEQKGik17FHqvrmDJ1gx7DNFY56m36We+Zpd9iPhHLx
d4PODh+SqIwo6t7b0JEuFuiLoU+tykkWPgPpI3OQpQkS6jOiTl1NMJbIFVCsQRuu
k1jhG33JOLQca63Vs6NzzI0O/ILso6P6tVYs+BnuwvywMBT3B1coWwgPHI+v1CNo
/W+AZpD8QDu09MocwvG5W/WdVVHzkv8eLH8tL6x5LWt3BOl04wUJpQxRFxioYaPx
nswCtDn8VYu8jsnP/vKMpui/1qpLp82cKND7k7204gP8jXiKedAIhv2+gPlj5sux
Zu+sen7Qq3fj43Lz24RSlueMO/8KCQu4LCj8RYDElwperxmbuaSppHGMJ46KgxYd
fIqHlj4ndAZU1M720itozJM7PSxquhk+m/bM/CrZABT9YJVCMhq2TRRI1Jjl7jgS
ebBhHEHzwEVXJZw4RKFkPmXH9V1Cb5auKLEgKbb25EjUekubaivGWJBy9gjg1ws2
tUmNT1AX5FZ2/y7wA8tFOFJeFATN4MA1IFHSDeEqAWadfGE7/w2ypyhhM+cswdMQ
82ll/IdnZtFgDaCR/qSz271OhNHklQIDAQABo1AwTjAdBgNVHQ4EFgQUE7mNv8ji
9Ra6TCq9TQF/2osx/3QwHwYDVR0jBBgwFoAUE7mNv8ji9Ra6TCq9TQF/2osx/3Qw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAZl9sLtmdElOT+mLT+7pp
1pq2zRhJScOPcJmtQD74ribpM/t/1Ys4ZfKxBZDxULRMJ1A7JAhxvKqtN+9uGY22
9RRQbXBVlJdvHJDn7YedN4PdmOgQEj671UwxulZtUECwVF56fTZlfCGMCBKocp/s
YHwQ7iV2J/vG6F0mlp4viWXfN1bY+eRe1YS03XLWXYoL0UvS94p3hbqcURtuLZnj
lEf1bhQ08Ju5hHmxxrlVcVnPDDK9jn26t+zBmbkMyEH2HLH4jUJG37jn6r8PHKnb
cyFZ69njjqYzrpqZj85vq2j4cbZ5bMY07F2mA5N9PsdNKhg9GB+p+eJQs6vTvRkV
My/3y7d3hr2BIKJ8TbY/USgTBdDOCbp30vflO6ZWFViSlm73ChTgJcwOPow2/NuC
DKw5kmwoCxTklK4Ehdx/H57Y/Xakq/sUVWo3HtUEY/3MUUNJnaA7UoFhxYsQTFPf
Q15Cbly9CHUkYsslVT2XxwUJ8jP295RpmWPh6iG9okBE8oUFxyPzMwduSW7cBqOt
LOK6c3K1zfMfSQhKPYK+2oHHoh0ipXxSiwHrRZh0hI62iJYiGl84pUP3vARSI6Ba
ieUuGbkoJo2yFkqrHl02wRhAg572Ji7AqJbThF7oh9/8+Ckq6B1cm4axFSEWOxG/
l9z+VItCgA4cG/LQtVCxPKI=
-----END CERTIFICATE-----"
